#======================================================================================================================+
# FIle:  Bubble_Sheet/src/Constants.py
# Project: OMR Scantron for FRC Team 5712
# Author:  William Bodeis <wdbodeis@gmail.com>
#-----------------------------------------------------------------------------------------------------------------------

class Constants():
    """
    This was created to be used for future years if the bubble sheet/Scantron is going to be used every year.
    It would be easier to quickly change out these values then going through each of the files. 
    It was also intended to reduce the clutter within the other files so there isn't hundreds of extra lines. When 
    reading through them. 
    """
    # OMR
    _key_column_index: tuple = (0, 8, 18, 26, 31, 39, 60, 74, 80, 94, 110, 124, 130, 136, 142)
    _total_key_values: int = 155
    _bubble_location: dict = {
                              # Column 1
                              0: [(1027, 2578), 'Auton HP TL'],
                              1: [(1027, 2758), 'Auton HP ML'],
                              2: [(1027, 2937), 'Auton HP LLCone'],
                              3: [(1027, 3117), 'Auton HP LLCube'],
                              4: [(1028, 4381), 'Tele HP TL'],
                              5: [(1028, 4562), 'Tele HP ML'],
                              6: [(1028, 4743), 'Tele HP LLCone'],
                              7: [(1028, 4924), 'Tele HP LLCube'],
                              # Column 2
                              8: [(1314, 1501), 'Blue Alliance'],
                              9: [(1315, 1680), 'Red Alliance'],
                              10: [(1316, 2576), 'Auton HP TM'],
                              11: [(1316, 2756), 'Auton HP MM'],
                              12: [(1316, 2937), 'Auton HP MLCone'],
                              13: [(1317, 3117), 'Auton HP MLCube'],
                              14: [(1316, 4380), 'Tele HP TM'],
                              15: [(1317, 4561), 'Tele HP MM'],
                              16: [(1316, 4743), 'Tele HP MLCone'],
                              17: [(1317, 4923), 'Tele HP MLCube'],
                              # Column 3
                              18: [(1605, 2576), 'Auton HP TR'],
                              19: [(1605, 2757), 'Auton HP MR'],
                              20: [(1605, 2936), 'Auton HP LRCone'], 
                              21: [(1606, 3116), 'Auton HP LRCube'],
                              22: [(1606, 4379), 'Tele HP TR'],
                              23: [(1607, 4561), 'Tele HP MR'],
                              24: [(1606, 4743), 'Tele HP LRCone'],
                              25: [(1606, 4923), 'Tele HP LRCube'],
                              # Column 4
                              26: [(1894, 5464), 'Floor Yes'],
                              27: [(1896, 5642), 'Single Sub Yes'], 
                              28: [(1895, 5826), 'Double Sub Slider Yes'],
                              29: [(1894, 6005), 'Double Sub Chute Yes'],
                              30: [(1893, 7088), 'Parked Yes'],
                              # Column 5
                              31: [(2184, 2576), 'Auton M TL'],
                              32: [(2184, 2756), 'Auton M ML'],
                              33: [(2184, 2937), 'Auton M LLCone'],
                              34: [(2184, 3117), 'Auton M LLCube'],
                              35: [(2184, 4380), 'Tele M TL'],
                              36: [(2184, 4561), 'Tele M ML'],
                              37: [(2184, 4742), 'Tele M LLCone'],
                              38: [(2184, 4923), 'Tele M LLCube'],
                              # Column 6
                              39: [(2472, 429), 'Match Deca Zero'],
                              40: [(2471, 608), 'Match Zero'],
                              41: [(2472, 1143), 'Team Kilo Zero'],
                              42: [(2472, 1321), 'Team Hecto Zero'],
                              43: [(2472, 1502), 'Team Deca Zero'],
                              44: [(2472, 1678), 'Team Zero'],
                              45: [(2473, 2576), 'Auton M TM'],
                              46: [(2473, 2756), 'Auton M MM'],
                              47: [(2474, 2936), 'Auton M MLCone'],
                              48: [(2474, 3117), 'Auton M MLCube'],
                              49: [(2474, 3479), 'Auton Charge Station On'],
                              50: [(2474, 4380), 'Tele M TM'],
                              51: [(2475, 4563), 'Tele M MM'],
                              52: [(2473, 4740), 'Tele M MLCone'],
                              53: [(2474, 4923), 'Tele M MLCube'],
                              54: [(2474, 5464), 'Floor No'],
                              55: [(2474, 5644), 'Single Sub No'],
                              56: [(2473, 5824), 'Double Sub Slider No'],
                              57: [(2473, 6004), 'Parked No'],
                              58: [(2473, 6547), 'End Game Charge Station On'],
                              59: [(2472, 7087), 'Parked No'],
                              # Column 7
                              60: [(2763, 430), 'Match Deca One'],
                              61: [(2763, 608), 'Match One'],
                              62: [(2762, 1144), 'Team Kilo One'],
                              63: [(2763, 1321), 'Team Hecto One'],
                              64: [(2762, 1500), 'Team Deca One'],
                              65: [(2763, 1679), 'Team One'],
                              66: [(2763, 2574), 'Auton M TR'],
                              67: [(2763, 2756), 'Auton M MR'],
                              68: [(2764, 2936), 'Auton M LRCone'],
                              69: [(2764, 3117), 'Auton M LRCube'],
                              70: [(2764, 4380), 'Tele M TR'],
                              71: [(2764, 4561), 'Tele M MR'],
                              72: [(2764, 4742), 'Tele M LRCone'],
                              73: [(2763, 4919), 'Tele M LRCube'],
                              # Column 8
                              74: [(3052, 430), 'Match Deca Two'],
                              75: [(3052, 609), 'Match Two'],
                              76: [(3052, 1143), 'Team Kilo Two'],
                              77: [(3052, 1322), 'Team Hecto Two'],
                              78: [(3053, 1501), 'Team Deca Two'],
                              79: [(3053, 1679), 'Team Two'],
                              # Column 9
                              80: [(3343, 429), 'Match Deca Three'],
                              81: [(3343, 608), 'Match Three'],
                              82: [(3342, 1143), 'Team Kilo Three'],
                              83: [(3343, 1321), 'Team Hecto Three'],
                              84: [(3343, 1500), 'Team Deca Three'],
                              85: [(3344, 1679), 'Team Three'],
                              86: [(3344, 2576), 'Auton ST TL'],
                              87: [(3344, 2756), 'Auton ST ML'],
                              88: [(3345, 2936), 'Auton ST LLCone'],
                              89: [(3345, 3116), 'Auton ST LLCube'],
                              90: [(3343, 4378), 'Tele ST TL'],
                              91: [(3344, 4561), 'Tele ST ML'],
                              92: [(3344, 4922), 'Tele ST LLCone'],
                              93: [(3345, 4741), 'Tele ST LLCube'],
                              # Column 10
                              94: [(3633, 429), 'Match Deca Four'],
                              95: [(3633, 607), 'Match Four'],
                              96: [(3633, 1142), 'Team Kilo Four'],
                              97: [(3633, 1321), 'Team Hecto Four'],
                              98: [(3634, 1499), 'Team Deca Four'],
                              99: [(3634, 1678), 'Team Four'],
                              100: [(3634, 2574), 'Auton ST TM'],
                              101: [(3635, 2755), 'Auton ST MM'],
                              102: [(3635, 2935), 'Auton ST MLCone'],
                              103: [(3635, 3115), 'Auton ST MLCube'],
                              104: [(3635, 3476), 'Auton Charge Station Balanced'],
                              105: [(3635, 4379), 'Tele ST TM'],
                              106: [(3635, 4560), 'Tele ST MM'],
                              107: [(3635, 4740), 'Tele ST MLCone'],
                              108: [(3635, 4921), 'Tele ST MLCube'],
                              109: [(3634, 6545), 'End Game Charge Station Balanced'],
                              # Column 11
                              110: [(3921, 428), 'Match Deca Five'],
                              111: [(3921, 607), 'Match Five'],
                              112: [(3921, 1141), 'Team Kilo Five'],
                              113: [(3921, 1319), 'Team Hecto Five'],
                              114: [(3922, 1498), 'Team Deca Five'],
                              115: [(3922, 1677), 'Team Five'],
                              116: [(3922, 2574), 'Auton ST TR'],
                              117: [(3923, 2754), 'Auton ST MR'],
                              118: [(3924, 2934), 'Auton ST LRCone'],
                              119: [(3923, 3114), 'Auton ST LRCube'],
                              120: [(3922, 4558), 'Tele ST TR'],
                              121: [(3923, 4378), 'Tele ST MR'],
                              122: [(3923, 4739), 'Tele ST LRCone'],
                              123: [(3923, 4921), 'Tele ST LRCube'],
                              # Column 12
                              124: [(4211, 427), 'Match Deca Six'],
                              125: [(4211, 606), 'Match Six'],
                              126: [(4211, 1140), 'Team Kilo Six'],
                              127: [(4211, 1319), 'Team Hecto Six'],
                              128: [(4211, 1497), 'Team Deca Six'],
                              129: [(4212, 1676), 'Team Six'],
                              # Column 13
                              130: [(4500, 426), 'Match Deca Seven'],
                              131: [(4500, 605), 'Match Seven'],
                              132: [(4500, 1139), 'Team Kilo Seven'],
                              133: [(4501, 1318), 'Team Hecto Seven'],
                              134: [(4501, 1497), 'Team Deca Seven'],
                              135: [(4501, 1676), 'Team Seven'],
                              # Column 14
                              136: [(4790, 604), 'Match Deca Eight'],
                              137: [(4791, 425), 'Match Eight'],
                              138: [(4791, 1139), 'Team Kilo Eight'],
                              139: [(4791, 1317), 'Team Hecto Eight'],
                              140: [(4791, 1494), 'Team Deca Eight'],
                              141: [(4791, 1674), 'Team Eight'],
                              # Column 15
                              142: [(5080, 424), 'Match Deca Nine'],
                              143: [(5080, 603), 'Match Nine'],
                              144: [(5080, 1138), 'Team Kilo Nine'],
                              145: [(5080, 1316), 'Team Hecto Nine'],
                              146: [(5080, 1494), 'Team Deca Nine'],
                              147: [(5079, 1673), 'Team Nine'],
                              148: [(5081, 2569), 'Left Community Yes'],
                              149: [(5081, 2750), 'Left Community No'],
                              150: [(5082, 3472), 'Auton Charge Station Not Attempted'],
                              151: [(5081, 5458), 'Travel Between HP and CS'],
                              152: [(5081, 5637), 'Travel Over Charge'],
                              153: [(5080, 5818), 'Travel Between ST and CS'],
                              154: [(5080, 6540), 'End Game Charge Station Not Attempted']
                              }
    # Scantrona
    _raw_data = {
                 'Team': [0, 0],
                 'Match': [1, 0],
                 'Alliance': [2, 0],
                 'Auton HP TL': [3, 0],
                 'Auton HP ML': [4, 0],
                 'Auton HP LLCube': [5, 0],
                 'Auton HP LLCone': [6, 0],
                 'Auton HP TM': [7, 0],
                 'Auton HP MM': [8, 0],
                 'Auton HP MLCube': [9, 0],
                 'Auton HP MLCone': [10, 0],
                 'Auton HP TR': [11, 0],
                 'Auton HP MR': [12, 0],
                 'Auton HP LRCube': [13, 0],
                 'Auton HP LRCone': [14, 0],
                 'Auton M TL': [15, 0],
                 'Auton M ML': [16, 0],
                 'Auton M LLCube': [17, 0],
                 'Auton M LLCone': [18, 0],
                 'Auton M TM': [19, 0],
                 'Auton M MM': [20, 0],
                 'Auton M MLCube': [21, 0],
                 'Auton M MLCone': [22, 0],
                 'Auton M TR': [23, 0],
                 'Auton M MR': [24, 0],
                 'Auton M LRCube': [25, 0],
                 'Auton M LRCone': [26, 0],
                 'Auton ST TL': [27, 0],
                 'Auton ST ML': [28, 0],
                 'Auton ST LLCube': [29, 0],
                 'Auton ST LLCone': [30, 0],
                 'Auton ST TM': [31, 0],
                 'Auton ST MM': [32, 0],
                 'Auton ST MLCube': [33, 0],
                 'Auton ST MLCone': [34, 0],
                 'Auton ST TR': [35, 0],
                 'Auton ST MR': [36, 0],
                 'Auton ST LRCube': [37, 0],
                 'Auton ST LRCone': [38, 0],
                 'Tele HP TL': [39, 0],
                 'Tele HP ML': [40, 0],
                 'Tele HP LLCube': [41, 0],
                 'Tele HP LLCone': [42, 0],
                 'Tele HP TM': [43, 0],
                 'Tele HP MM': [44, 0],
                 'Tele HP MLCube': [45, 0],
                 'Tele HP MLCone': [46, 0],
                 'Tele HP TR': [47, 0],
                 'Tele HP MR': [48, 0],
                 'Tele HP LRCube': [49, 0],
                 'Tele HP LRCone': [50, 0],
                 'Tele M TL': [51, 0],
                 'Tele M ML': [52, 0],
                 'Tele M LLCube': [53, 0],
                 'Tele M LLCone': [54, 0],
                 'Tele M TM': [55, 0],
                 'Tele M MM': [56, 0],
                 'Tele M MLCube': [57, 0],
                 'Tele M MLCone': [58, 0],
                 'Tele M TR': [59, 0],
                 'Tele M MR': [60, 0],
                 'Tele M LRCube': [61, 0],
                 'Tele M LRCone': [62, 0],
                 'Tele ST TL': [63, 0],
                 'Tele ST ML': [64, 0],
                 'Tele ST LLCube': [65, 0],
                 'Tele ST LLCone': [66, 0],
                 'Tele ST TM': [67, 0],
                 'Tele ST MM': [68, 0],
                 'Tele ST MLCube': [69, 0],
                 'Tele ST MLCone': [70, 0],
                 'Tele ST TR': [71, 0],
                 'Tele ST MR': [72, 0],
                 'Tele ST LRCube': [73, 0],
                 'Tele ST LRCone': [74, 0],
                 'Community': [75, 0],
                 'Auton Charge Station': [76, 0],
                 'Floor': [77, 0],
                 'Single Sub': [78, 0],
                 'Slider': [79, 0],
                 'Chute': [80, 0],
                 'HP & CS': [81, 0],
                 'Over Charge': [82, 0],
                 'ST & CS': [83, 0],
                 'Tele Charge Station': [84, 0],
                 'Parked': [85, 0]
                 }
    _team_number_location = {
                             41: [0, 0],
                             42: [0, 1],
                             43: [0, 2],
                             44: [0, 3],
                             62: [1, 0],
                             63: [1, 1],
                             64: [1, 2],
                             65: [1, 3],
                             76: [2, 0],
                             77: [2, 1],
                             78: [2, 2],
                             79: [2, 3],
                             82: [3, 0],
                             83: [3, 1],
                             84: [3, 2],
                             85: [3, 3],
                             96: [4, 0],
                             97: [4, 1],
                             98: [4, 2],
                             99: [4, 3],
                             112: [5, 0],
                             113: [5, 1],
                             114: [5, 2],
                             115: [5, 3],
                             126: [6, 0],
                             127: [6, 1],
                             128: [6, 2],
                             129: [6, 3],
                             132: [7, 0],
                             133: [7, 1],
                             134: [7, 2],
                             135: [7, 3],
                             138: [8, 0],
                             139: [8, 1],
                             140: [8, 2],
                             141: [8, 3],
                             144: [9, 0],
                             145: [9, 1],
                             146: [9, 2],
                             147: [9, 3]
                             }
    _match_number_location = {
                              39: [0, 0],
                              40: [0, 1],
                              60: [1, 0],
                              61: [1, 1],
                              74: [2, 0],
                              75: [2, 1],
                              80: [3, 0],
                              81: [3, 1],
                              94: [4, 0],
                              95: [4, 1],
                              110: [5, 0],
                              111: [5, 1],
                              124: [6, 0],
                              125: [6, 1],
                              130: [7, 0],
                              131: [7, 1],
                              136: [8, 0],
                              137: [8, 1],
                              142: [9, 0],
                              143: [9, 1]
                              }
    _alliance_location = {
                          8: [0],
                          9: [1]
                          }
    _game_red_results_locations: dict = {
                                         0: 'Auton HP TL',
                                         1: 'Auton HP ML',
                                         2: 'Auton HP LLCone',
                                         3: 'Auton HP LLCube',
                                         4: 'Tele HP TL',
                                         5: 'Tele HP ML',
                                         6: 'Tele HP LLCone',
                                         7: 'Tele HP LLCube',
                                         10: 'Auton HP TM',
                                         11: 'Auton HP MM',
                                         12: 'Auton HP MLCone',
                                         13: 'Auton HP MLCube',
                                         14: 'Tele HP TM',
                                         15: 'Tele HP MM',
                                         16: 'Tele HP MLCone',
                                         17: 'Tele HP MLCube',
                                         18: 'Auton HP TR',
                                         19: 'Auton HP MR',
                                         20: 'Auton HP LRCone',
                                         21: 'Auton HP LRCube',
                                         22: 'Tele HP TR',
                                         23: 'Tele HP MR',
                                         24: 'Tele HP LRCone',
                                         25: 'Tele HP LRCube',
                                         31: 'Auton M TL',
                                         32: 'Auton M ML',
                                         33: 'Auton M LLCone',
                                         34: 'Auton M LLCube',
                                         35: 'Tele M TL',
                                         36: 'Tele M ML',
                                         37: 'Tele M LLCone',
                                         38: 'Tele M LLCube',
                                         45: 'Auton M TM',
                                         46: 'Auton M MM',
                                         47: 'Auton M MLCone',
                                         48: 'Auton M MLCube',
                                         50: 'Tele M TM',
                                         51: 'Tele M MM',
                                         52: 'Tele M MLCone',
                                         53: 'Tele M MLCube',
                                         66: 'Auton M TR',
                                         67: 'Auton M MR',
                                         68: 'Auton M LRCone',
                                         69: 'Auton M LRCube',
                                         70: 'Tele M TR',
                                         71: 'Tele M MR',
                                         72: 'Tele M LRCone',
                                         73: 'Tele M LRCube',
                                         86: 'Auton ST TL',
                                         87: 'Auton ST ML',
                                         88: 'Auton ST LLCone',
                                         89: 'Auton ST LLCube',
                                         90: 'Tele ST TL',
                                         91: 'Tele ST ML',
                                         92: 'Tele ST LLCone',
                                         93: 'Tele ST LLCube',
                                         100: 'Auton ST TM',
                                         101: 'Auton ST MM',
                                         102: 'Auton ST MLCone',
                                         103: 'Auton ST MLCube',
                                         105: 'Tele ST TM',
                                         106: 'Tele ST MM',
                                         107: 'Tele ST MLCone',
                                         108: 'Tele ST MLCube',
                                         116: 'Auton ST TR',
                                         117: 'Auton ST MR',
                                         118: 'Auton ST LRCone',
                                         119: 'Auton ST LRCube',
                                         120: 'Tele ST TR',
                                         121: 'Tele ST MR',
                                         122: 'Tele ST LRCone',
                                         123: 'Tele ST LRCube'
                                         }
    _game_blue_results_locations = {
                                    0: 'Auton ST TL',
                                    1: 'Auton ST ML',
                                    2: 'Auton ST LLCone',
                                    3: 'Auton ST LLCube',
                                    4: 'Tele ST TL',
                                    5: 'Tele ST ML',
                                    6: 'Tele ST LLCone',
                                    7: 'Tele ST LLCube',
                                    10: 'Auton ST TM',
                                    11: 'Auton ST MM',
                                    12: 'Auton ST MLCone',
                                    13: 'Auton ST MLCube',
                                    14: 'Tele ST TM',
                                    15: 'Tele ST MM',
                                    16: 'Tele ST MLCone',
                                    17: 'Tele ST MLCube',
                                    18: 'Auton ST TR',
                                    19: 'Auton ST MR',
                                    20: 'Auton ST LRCone',
                                    21: 'Auton ST LRCube',
                                    22: 'Tele ST TR',
                                    23: 'Tele ST MR',
                                    24: 'Tele ST LRCone',
                                    25: 'Tele ST LRCube',
                                    31: 'Auton M TL',
                                    32: 'Auton M ML',
                                    33: 'Auton M LLCone',
                                    34: 'Auton M LLCube',
                                    35: 'Tele M TL',
                                    36: 'Tele M ML',
                                    37: 'Tele M LLCone',
                                    38: 'Tele M LLCube',
                                    45: 'Auton M TM',
                                    46: 'Auton M MM',
                                    47: 'Auton M MLCone',
                                    48: 'Auton M MLCube',
                                    50: 'Tele M TM',
                                    51: 'Tele M MM',
                                    52: 'Tele M MLCone',
                                    53: 'Tele M MLCube',
                                    66: 'Auton M TR',
                                    67: 'Auton M MR',
                                    68: 'Auton M LRCone',
                                    69: 'Auton M LRCube',
                                    70: 'Tele M TR',
                                    71: 'Tele M MR',
                                    72: 'Tele M LRCone',
                                    73: 'Tele M LRCube',
                                    86: 'Auton HP TL',
                                    87: 'Auton HP ML',
                                    88: 'Auton HP LLCone',
                                    89: 'Auton HP LLCube',
                                    90: 'Tele HP TL',
                                    91: 'Tele HP ML',
                                    92: 'Tele HP LLCone',
                                    93: 'Tele HP LLCube',
                                    100: 'Auton HP TM',
                                    101: 'Auton HP MM',
                                    102: 'Auton HP MLCone',
                                    103: 'Auton HP MLCube',
                                    105: 'Tele HP TM',
                                    106: 'Tele HP MM',
                                    107: 'Tele HP MLCone',
                                    108: 'Tele HP MLCube',
                                    116: 'Auton HP TR',
                                    117: 'Auton HP MR',
                                    118: 'Auton HP LRCone',
                                    119: 'Auton HP LRCube',
                                    120: 'Tele HP TR',
                                    121: 'Tele HP MR',
                                    122: 'Tele HP LRCone',
                                    123: 'Tele HP LRCube'
                                    }
    _play_style_location = {
                            26: 'Floor Yes',
                            27: 'Single Sub Yes',
                            28: 'Double Sub Slider Yes',
                            29: 'Double Sub Chute Yes',
                            30: 'Parked Yes',
                            49: 'Auton Charge Station On',
                            54: 'Floor No',
                            55: 'Single Sub No',
                            56: 'Double Sub Slider No',
                            57: 'Parked No',
                            58: 'End Game Charge Station On',
                            59: 'Parked No',
                            104: 'Auton Charge Station Balanced',
                            109: 'End Game Charge Station Balanced',
                            148: 'Left Community Yes',
                            149: 'Left Community No',
                            150: 'Auton Charge Station Not Attempted',
                            151: 'Travel Between HP and CS',
                            152: 'Travel Over Charge',
                            153: 'Travel Between ST and CS',
                            154: 'End Game Charge Station Not Attempted'
                            }

