raw_data: dict = {
0: ['','Team'],
1: ['','Match'],
2: ['','Alliance'],
3: ['','HP TL'],
4: ['','HP ML'],
5: ['','HP LLCube'],
6: ['','HP LLCone'],
7: ['','HP TM '],
8: ['','HP MM'],
9: ['','HP MLCube'],
10: ['','HP MLCone'],
11: ['','HP TR'],
12: ['','HP MR'],
13: ['','HP LRCube'],
14: ['','HP LRCone'],
15: ['','M TL'],
16: ['','M ML'],
17: ['','M LLCube'],
18: ['','M LLCone'],
19: ['','M TM '],
20: ['','M MM'],
21: ['','M MLCube'],
22: ['','M MLCone'],
23: ['','M TR'],
24: ['','M MR'],
25: ['','M LRCube'],
26: ['','M LRCone'],
27: ['','ST TL'],
28: ['','ST ML'],
29: ['','ST LLCube'],
30: ['','ST LLCone'],
31: ['','ST TM '],
32: ['','ST MM'],
33: ['','ST MLCube'],
34: ['','ST MLCone'],
35: ['','ST TR'],
36: ['','ST MR'],
37: ['','ST LRCube'],
38: ['','ST LRCone'],
39: ['','HP TL'],
40: ['','HP ML'],
41: ['','HP LLCube'],
42: ['','HP LLCone'],
43: ['','HP TM '],
44: ['','HP MM'],
45: ['','HP MLCube'],
46: ['','HP MLCone'],
47: ['','HP TR'],
48: ['','HP MR'],
49: ['','HP LRCube'],
50: ['','HP LRCone'],
51: ['','M TL'],
52: ['','M ML'],
53: ['','M LLCube'],
54: ['','M LLCone'],
55: ['','M TM '],
56: ['','M MM'],
57: ['','M MLCube'],
58: ['','M MLCone'],
59: ['','M TR'],
60: ['','M MR'],
61: ['','M LRCube'],
62: ['','M LRCone'],
63: ['','ST TL'],
64: ['','ST ML'],
65: ['','ST LLCube'],
66: ['','ST LLCone'],
67: ['','ST TM '],
68: ['','ST MM'],
69: ['','ST MLCube'],
70: ['','ST MLCone'],
71: ['','ST TR'],
72: ['','ST MR'],
73: ['','ST LRCube'],
74: ['','ST LRCone'],
75: ['','Community'],
76: ['','Charge Station'],
77: ['','Floor'],
78: ['','Single Sub'],
79: ['','Slider'],
80: ['','Chute'],
81: ['','HP & CS'],
82: ['','Over Charge'],
83: ['','ST & CS'],
84: ['','Charge Station'],
85: ['','Parked']
}