raw_data: dict = {
'Team': [0, ''],
'Match': [1, ''],
'Alliance': [2, ''],
'HP TL': [3, ''],
'HP ML': [4, ''],
'HP LLCube': [5, ''],
'HP LLCone': [6, ''],
'HP TM ': [7, ''],
'HP MM': [8, ''],
'HP MLCube': [9, ''],
'HP MLCone': [10, ''],
'HP TR': [11, ''],
'HP MR': [12, ''],
'HP LRCube': [13, ''],
'HP LRCone': [14, ''],
'M TL': [15, ''],
'M ML': [16, ''],
'M LLCube': [17, ''],
'M LLCone': [18, ''],
'M TM ': [19, ''],
'M MM': [20, ''],
'M MLCube': [21, ''],
'M MLCone': [22, ''],
'M TR': [23, ''],
'M MR': [24, ''],
'M LRCube': [25, ''],
'M LRCone': [26, ''],
'ST TL': [27, ''],
'ST ML': [28, ''],
'ST LLCube': [29, ''],
'ST LLCone': [30, ''],
'ST TM ': [31, ''],
'ST MM': [32, ''],
'ST MLCube': [33, ''],
'ST MLCone': [34, ''],
'ST TR': [35, ''],
'ST MR': [36, ''],
'ST LRCube': [37, ''],
'ST LRCone': [38, ''],
'HP TL': [39, ''],
'HP ML': [40, ''],
'HP LLCube': [41, ''],
'HP LLCone': [42, ''],
'HP TM ': [43, ''],
'HP MM': [44, ''],
'HP MLCube': [45, ''],
'HP MLCone': [46, ''],
'HP TR': [47, ''],
'HP MR': [48, ''],
'HP LRCube': [49, ''],
'HP LRCone': [50, ''],
'M TL': [51, ''],
'M ML': [52, ''],
'M LLCube': [53, ''],
'M LLCone': [54, ''],
'M TM ': [55, ''],
'M MM': [56, ''],
'M MLCube': [57, ''],
'M MLCone': [58, ''],
'M TR': [59, ''],
'M MR': [60, ''],
'M LRCube': [61, ''],
'M LRCone': [62, ''],
'ST TL': [63, ''],
'ST ML': [64, ''],
'ST LLCube': [65, ''],
'ST LLCone': [66, ''],
'ST TM ': [67, ''],
'ST MM': [68, ''],
'ST MLCube': [69, ''],
'ST MLCone': [70, ''],
'ST TR': [71, ''],
'ST MR': [72, ''],
'ST LRCube': [73, ''],
'ST LRCone': [74, ''],
'Community': [75, ''],
'Charge Station': [76, ''],
'Floor': [77, ''],
'Single Sub': [78, ''],
'Slider': [79, ''],
'Chute': [80, ''],
'HP & CS': [81, ''],
'Over Charge': [82, ''],
'ST & CS': [83, ''],
'Charge Station': [84, ''],
'Parked': [85, ''],
}