scoring_columns: tuple = (
'Team Number',
'Match Number',
'Alliance',
'Auton HP TL',
'Auton HP ML',
'Auton HP LLCube',
'Auton HP LLCone',
'Auton HP TM',
'Auton HP MM',
'Auton HP MLCube',
'Auton HP MLCone',
'Auton HP TR',
'Auton HP MR',
'Auton HP LRCube',
'Auton HP LRCone',
'Auton M TL',
'Auton M ML',
'Auton M LLCube',
'Auton M LLCone',
'Auton M TM',
'Auton M MM',
'Auton M MLCube',
'Auton M MLCone',
'Auton M TR',
'Auton M MR',
'Auton M LRCube',
'Auton M LRCone',
'Auton ST TL',
'Auton ST ML',
'Auton ST LLCube',
'Auton ST LLCone',
'Auton ST TM',
'Auton ST MM',
'Auton ST MLCube',
'Auton ST MLCone',
'Auton ST TR',
'Auton ST MR',
'Auton ST LRCube',
'Auton ST LRCone',
'Tele HP TL',
'Tele HP ML',
'Tele HP LLCube',
'Tele HP LLCone',
'Tele HP TM',
'Tele HP MM',
'Tele HP MLCube',
'Tele HP MLCone',
'Tele HP TR',
'Tele HP MR',
'Tele HP LRCube',
'Tele HP LRCone',
'Tele M TL',
'Tele M ML',
'Tele M LLCube',
'Tele M LLCone',
'Tele M TM',
'Tele M MM',
'Tele M MLCube',
'Tele M MLCone',
'Tele M TR',
'Tele M MR',
'Tele M LRCube',
'Tele M LRCone',
'Tele ST TL',
'Tele ST ML',
'Tele ST LLCube',
'Tele ST LLCone',
'Tele ST TM',
'Tele ST MM',
'Tele ST MLCube',
'Tele ST MLCone',
'Tele ST TR',
'Tele ST MR',
'Tele ST LRCube',
'Tele ST LRCone',
'Community',
'Charge Station',
'Floor',
'Single Sub',
'Slider',
'Chute',
'HP & CS',
'Over Charge',
'ST & CS',
'Charge Station',
'Parked'
)